### ISSUE TITLE
Input in spot exposure mapping

### ISSUE THREAD

**Issue by dim162** [aurelienpierre/R-Darktable#12]
Did I miss something? I pick a region bright or obscure, the rectangle input in spot exposure mapping remains the same (black). The target strip & lightness cursor follow the picker. The spot mode is on correction.

* darktable version : Last R-Dt
* OS                : xfce 22.04/linux 5.15
* Linux - Distro    : Ubuntu Studio 22.04
* Graphics card     : Geforce 1050 Ti
* Graphics driver   : 470
* OpenCL installed  : y
* OpenCL activated  : y

**Comment by todd-prior** [comment]
Measure to sample correct to apply??

**Comment by dim162** [comment]
In exposure>>spot exposure mapping, with spot mode on measure, i pick up lightness, on bright surface. The rectangle input remains black, in correction mode the same.

**Comment by dim162** [comment]
I "solved" the problem, it seems, it was linked to opencl. The package's installation had some issues
