### ISSUE TITLE
raw chromatic aberration module disappeared

### ISSUE THREAD

**Issue by dim162** [aurelienpierre/R-Darktable#14]
The raw chromatic aberration module has disappeared, even from manage preset 

    darktable version : Last R-Dt
    OS : xfce 22.04/linux 5.15
    Linux - Distro : Ubuntu Studio 22.04
    Graphics card : Geforce 1050 Ti
    Graphics driver : 470
    OpenCL installed : y
    OpenCL activated : y

**Comment by janfri** [comment]
It is deprecated: https://github.com/aurelienpierre/R-Darktable/wiki#modules-deprecated

**Comment by dim162** [comment]
I miss it. thank you
