### ISSUE TITLE
Timeline empty

### ISSUE THREAD

**Issue by dim162** [aurelienpierre/R-Darktable#15]
After update, the time remains empty

* kernel 5.15.0-41
* Linux - Distro    :Ubuntu 22.04 studio
* Memory            : 32Gb
* Graphics card     : 2x Geforce 
* Graphics driver   : 470
* OpenCL installed  : Y
* OpenCL activated  : Y
* Xorg              : 
* Desktop           : xfce
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  :

**Comment by dim162** [comment]
I try to reinstall from a fresh git download, & i have a build error
![Screenshot_2022-07-15_20-21-14](https://user-images.githubusercontent.com/10468352/179287537-6e9ffe0b-d39a-4006-8e17-14098a705c9b.png)

**Comment by amousset** [comment]
If you are talking about the pictures timeline in the lower part of the lighttable it is voluntarily [removed ](https://github.com/aurelienpierre/R-Darktable/wiki#features)from this fork:

> the [timeline](https://docs.darktable.org/usermanual/3.8/en/module-reference/utility-modules/lighttable/timeline/) : too complicated for the little it does. LOSS OF CPU CYCLES.

**Comment by dim162** [comment]
I download the rdarktable dependencies & sources &  as explain in Rdarktable github, i use terminal commands from Rdarktable github & i had this error. Before the last update, i had a normal timeline. I can understand the choice to remove it, but in the previous version, it was not removed & with the last version, it creates an error during compilation!

**Comment by ptilopteri** [comment]
compiles fine for me on openSUSE Tumbleweed ???

**Comment by dim162** [comment]
I'm on Ubuntu 22.04 which are one of the [recommended & tested OS](url)

**Comment by aurelienpierre** [comment]
The timeline has been removed (terrible code and performance loss).

If your building process still tries to compile it, maybe it is because you have leftovers from upstream darktable or something. Try building with `sh build.sh --clean-all` to ensure everything is cleaned.

**Comment by marcsitkin** [comment]
Noticed today that the space the timeline used to occupy on the lightable is still present but empty, although a couple ctrl-b taps will clear it.
Personally, I'm happy it's gone, but the space should be reclaimed by default.

**Comment by aurelienpierre** [comment]
Right, I will have a look.

**Comment by dim162** [comment]
> 



> The timeline has been removed (terrible code and performance loss).

R-Darktable is responsive, that's great. I didn't use the timeline very often. A very annoying  trick is the tooltips... I had to enable compositor of the desktop, which consume à lot of ressources too

> If your building process still tries to compile it, maybe it is because you have leftovers from upstream darktable or something. Try building with `sh build.sh --clean-all` to ensure everything is cleaned.

It was a new & clean installation. I had a lot of errors. With the last RDt updates, it'ok. RDt is simple, efficient. i can do what i want without spending a lot of time & patience.

**Comment by aurelienpierre** [comment]
The empty bottom panel in lighttable should be fixed now.
