### ISSUE TITLE
Thumbnail Information overlays  

### ISSUE THREAD

**Issue by davidfvj** [aurelienpierre/R-Darktable#27]
The information overlays that should be seen on the lighttable thumbnails are missing.

**Comment by ptilopteri** [comment]
you might take a few moments and describe what you believe
you should see, what you do see and what you believe is missing, 
what version of R-Darktable and some information about your
operating system
just so it does not need to be requested later and the developer's 
time is relegated to a fix rather than extracting information one would
be expected to provide.

**Comment by davidfvj** [comment]
3.9.0+1720~g501fbbf7e ... Manjaro/Arch/XFCE
When mousing over the 'thumbnails' in the Lighttable view I expected to see file information for the relevant image. This information is NOT SHOWN.

**Comment by davidfvj** [comment]
I think it is important to be able to compare camera settings of adjacent but similar images. This is the use to which I put this feature.

**Comment by aadm** [comment]
> 3.9.0+1720~g501fbbf7e ... Manjaro/Arch/XFCE When mousing over the 'thumbnails' in the Lighttable view I expected to see file information for the relevant image. This information is NOT SHOWN.

Have you read the wiki? It is written clearly that this is one of the things that have been removed intentionally from Aurelien:

https://github.com/aurelienpierre/R-Darktable/wiki#what-was-removed-from-mainstream-darktable

However, this was also something that bothered me and I mentioned this in the general forum-like "Discussions", to which Aurelien commented extensively:

https://github.com/aurelienpierre/R-Darktable/discussions/21#discussioncomment-3171327

I'm now getting used to *not* see the captions below the thumbnails, and I rely on the Display Metadata module as AP suggested, but I'd still love to see a minimal set of infos below thumbnails like file or version name, shooting parameters etc.  But according to AP this causes loss of CPU cycles so I don't see this happening.

(I still have the feeling that the dynamic captions appearing when hovering on a thumbnail, i,.e. what you're asking, are more cpu-hungry than the "static" captions I wanted...)

**Comment by davidfvj** [comment]
OK ... I now better understand the situation. I certainly can use the EXIF sidebar to achieve similar results.
